### ISSUE TITLE
Mesher missing?

### ISSUE THREAD

**Issue by esteimle** [MIT-SPARK/Kimera-VIO#105]
Where's the mesher portion?  The links to it just bring you back to the VIO?  Am I missing something :)  ?

**Comment by ToniRV** [comment]
The per-frame mesh is inside Kimera-VIO in fact!
Check the https://github.com/MIT-SPARK/Kimera-VIO/tree/master/include/kimera-vio/mesh files.
For the global mesh: check https://github.com/MIT-SPARK/Kimera-Semantics
