### ISSUE TITLE
Can not seen the meshing in the windows

### ISSUE THREAD

**Issue by tftangming** [MIT-SPARK/Kimera-VIO#106]
**Description:**
When I run the program in the datasets V2_03_difficult, I can see the camera moving in the windows, but can not see the meshing process. What it happen, and if the program can generate mesh without kimera sementic?
**Command:**
```
# replace this line with the command(s) you used
```

**Console output:**
```

# remove this line and paste your console output HERE - no screenshots please

```

**Additional files:**
Please attach all the files needed to reproduce the error.

Please give also the following information:
* Kimera-Vio branch, tag or commit used
* GTSAM version used:
* OpenGV version used:
* OpenCV version used: type `opencv_version`
* Operating system and version (e.g. Ubuntu 16.04 or Windows 10): 
* Did you change the source code? (yes / no):

**Comment by ToniRV** [comment]
I accidentally switched off the visualization of the mesh, it should now be fixed, feel free to re-open if it isn't the case.
