### ISSUE TITLE
Mesher dies

### ISSUE THREAD

**Issue by gaotao19890725** [MIT-SPARK/Kimera-VIO#108]
**Description:**
I0820 11:47:13.009541 24851 Pipeline.cpp:453] Shutting down VIO, reason: input is empty and threads are idle.
I0820 11:47:13.009613 24851 Pipeline.cpp:494] Shutting down VIO pipeline.
I0820 11:47:13.009632 24851 Pipeline.cpp:500] Calling registered shutdown callbacks...
I0820 11:47:13.009649 24851 DataProviderInterface.cpp:72] Shutting down DataProviderInterface.
I0820 11:47:13.009711 24851 Visualizer3DModule.cpp:98] Shutting down queues for: Visualizer
W0820 11:47:13.009816 24856 PipelineModule.h:397] Module: VioFrontEnd - Input queue: stereo_frontend_input_queue didn't return an output.
W0820 11:47:13.009941 24861 Visualizer3DModule.cpp:63] Module: Visualizer - visualizer_backend_queue queue is down
W0820 11:47:13.010116 24848 PipelineModule.h:545] Module: Display - Input queue: display_input_queue didn't return an output.
W0820 11:47:13.010296 24850 Pipeline.cpp:333] Not spinning pipeline as it's been shutdown.
W0820 11:47:13.010306 24860 PipelineModule.h:397] Module: VioBackEnd - Input queue: backend_input_queue didn't return an output.
W0820 11:47:13.011420 24851 Pipeline.cpp:887] No mesher thread, not joining.
W0820 11:47:13.011481 24851 Pipeline.cpp:887] No lcd thread, not joining.
I0820 11:47:13.011565 24851 Pipeline.cpp:514] VIO Pipeline's threads shutdown successfully.
VIO Pipeline successful shutdown.
W0820 11:47:13.011777 24848 KimeraVIO.cpp:111] Spin took: 141784 ms.
I0820 11:47:13.011812 24848 KimeraVIO.cpp:112] Pipeline successful? Yes!
I0820 11:47:13.011839 24848 Logger.cpp:58] Opening output file: output_timingOverall.csv
I0820 11:47:13.018201 24848 Logger.cpp:46] Closing output file: output_timingOverall.csv
I0820 11:47:13.018302 24848 Pipeline.cpp:279] Pipeline destructor called.
I0820 11:47:13.018322 24848 Pipeline.cpp:284] Manual shutdown was requested.
I0820 11:47:13.034049 24848 OpenCvVisualizer3D.cpp:92] OpenCvVisualizer3D destructor called.
I0820 11:47:13.037235 24848 VioBackEnd.h:87] Backend destructor called.
I0820 11:47:13.090025 24848 StereoVisionFrontEnd.h:63] StereoVisionFrontEnd destructor called.
I0820 11:47:13.251526 24848 EurocDataProvider.cpp:89] ETHDatasetParser destructor called.
I0820 11:47:13.263314 24848 DataProviderInterface.cpp:31] Data provider destructor called.
gaotao@gaotao-desktop:~/data/Kimera-VIO$ 

**Command:**
```
# replace this line with the command(s) you used
```

**Console output:**
```

# remove this line and paste your console output HERE - no screenshots please

```

**Additional files:**
Please attach all the files needed to reproduce the error.

Please give also the following information:
* Kimera-Vio branch, tag or commit used
* GTSAM version used:
* OpenGV version used:
* OpenCV version used: type `opencv_version`
* Operating system and version (e.g. Ubuntu 16.04 or Windows 10): 
* Did you change the source code? (yes / no):

**Comment by ToniRV** [comment]
I think this issue should be solved now, feel free to re-open!
