### ISSUE TITLE
Path planning and obstacle avoidance?

### ISSUE THREAD

**Issue by SebastienFerrero** [MIT-SPARK/Kimera-VIO#11]
Great work, powerful tool,  thanks for making it open source. Could you please outline how could this used for path planning and obstacle avoidance?
 According to my modest knowledge voxblox uses ESDF  which are a voxel grid where every point contains its Euclidean distance to the nearest obstacle. In voxblox, authors create ESDF from TSDF to be used for local and global path planning.

BEST REGARDS
thanks again

**Comment by ToniRV** [comment]
[Kimera-Semantics](https://github.com/MIT-SPARK/Kimera-Semantics) still builds a TSDF implicitly, so it would be possible to generate an ESDF as well, unfortunately, that is still not fully implemented (although it should be easy!).
