### ISSUE TITLE
Full Map

### ISSUE THREAD

**Issue by androclassic** [MIT-SPARK/Kimera-VIO#12]
Is there any way to visualize and save the multi frame mesh of the map ?

**Comment by ToniRV** [comment]
Hi @androclassic,

Inside `params/flags/Mesher.flags` you can set `--reduce_mesh_to_time_horizon` to false, to get the full multi-frame mesh (that will certainly slow down the pipeline though).
Saving the full mesh to a ply is not fully supported, but it is not too complicated, I add this in my todo list and will open a pull request asap.

Thanks
