### ISSUE TITLE
Does Kimera-Vio update the camera extrinsic calibration? 

### ISSUE THREAD

**Issue by ihamieh** [MIT-SPARK/Kimera-VIO#124]
I'm not sure if Kimera-VIO outputs or updates the camera extrinsic calibration? Also, does it output camera and IMU trajectories? I think it does but I'm not sure about camera extrinsics? can someone please let me know?

**Comment by marcusabate** [comment]
Kimera does not have any online extrinsic calibration in its current form, however this has been implemented and may be released soon. If you want to do your own implementation take a look at gtsam's SmartProjectionFactor (we currently use SmartProjectionPoseFactor)
