### ISSUE TITLE
What the strategy of switch between PreintegratedImuMeasurement and PreintegratedCombinedMeasurement in IMU front-end?

### ISSUE THREAD

**Issue by rginjapan** [MIT-SPARK/Kimera-VIO#132]
as the title, thanks ahead!

**Comment by ToniRV** [comment]
This switch is mostly for testing, I don't switch btw one and the other at runtime, but rather allow one or the other, just to compare performance.
I've seen that both give similar results, so feel free to use one or the other. (grosso modo: Combined just abstracts some bookkeeping compared to the regular one, which requires you to add a BetweenFactor for the IMU bias yourself).
