### ISSUE TITLE
Symbol lookup error when starting Kimera in Euroc's dataset

### ISSUE THREAD

**Issue by RachidaSK** [MIT-SPARK/Kimera-VIO#146]
**Description:**
Getting symbol lookup error when running Kimera in Euroc's dataset as described in the README.
**Command:**
```
bash ./scripts/stereoVIOEuroc.bash -p ~/rachida/dataset/Euroc/V1_01_easy
```

**Console output:**
```
(base) user@cream-ai:~/rachida/project/Kimera-VIO$ bash ./scripts/stereoVIOEuroc.bash -p ~/rachida/dataset/Euroc/V1_01_easy
Using dataset at path: /home/rachida/dataset/Euroc/V1_01_easy
 Launching:

            ██╗  ██╗██╗███╗   ███╗███████╗██████╗  █████╗
            ██║ ██╔╝██║████╗ ████║██╔════╝██╔══██╗██╔══██╗
            █████╔╝ ██║██╔████╔██║█████╗  ██████╔╝███████║
            ██╔═██╗ ██║██║╚██╔╝██║██╔══╝  ██╔══██╗██╔══██║
            ██║  ██╗██║██║ ╚═╝ ██║███████╗██║  ██║██║  ██║
            ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝

 
../build/stereoVIOEuroc: symbol lookup error: /home/rachida/project/Kimera-VIO/build/libkimera_vio.so: undefined symbol: _ZNK5gtsam13HessianFactor15hessianDiagonalEv
```

**Additional files:**
N/A

Please give also the following information:
* Kimera-Vio: commit f78e55978a46a7056d733e36489b8375a0807b94
* GTSAM version used: `version 4.0.3`
* OpenGV version used: commit 91f4b19c73450833a40e463ad3648aae80b3a7f3
* OpenCV version used: type `opencv_3.3.1`
* Operating system and version:  `Ubuntu 16.04`
* Did you change the source code? (yes / no): no

**Comment by ToniRV** [comment]
Same as #127
