### ISSUE TITLE
Broken link to Jupyter notebooks

### ISSUE THREAD

**Issue by dwisth** [MIT-SPARK/Kimera-VIO#151]
**Description:**

The links to the Jupyter notebooks on [this page](https://github.com/MIT-SPARK/Kimera-VIO/blob/master/docs/kimera_vio_debug_evaluation.md) are broken.

**Comment by marcusabate** [comment]
Will push a fix to the documentation, for future visitors these scripts are now located in [Kimera-VIO-Evaluation](https://github.com/MIT-SPARK/Kimera-VIO-Evaluation)
