### ISSUE TITLE
Loopclosure with Mono Frontend

### ISSUE THREAD

**Issue by lperruch** [MIT-SPARK/Kimera-VIO#164]
Hello,

Loop closure is currently not working with the mono frontend. Any reason for that? Is it planned to add it in the future?

Thanks

**Comment by marcusabate** [comment]
Yes, in the next update to this repo we will support loop closure in mono (using PnP). This should be out very soon.

**Comment by ssemenova** [comment]
Was the update ever released?

**Comment by neliudochka** [comment]
Loop closure still doesn't work. Any ideas why?
