### ISSUE TITLE
GTSAM_TANGENT_PREINTEGRATION

### ISSUE THREAD

**Issue by soldierofhell** [MIT-SPARK/Kimera-VIO#173]
Hi,
Kimera-VIO requires GTSAM_TANGENT_PREINTEGRATION to be disabled (=OFF). According to gtsam doc [The Preintegrated IMU Factor](https://gtsam.org/notes/IMU-Factor.html)
```
In GTSAM 4 a new and more efficient implementation, based on integrating on the NavState tangent space and detailed in docs/ImuFactor.pdf, is enabled by default. To switch to the RSS 2015 version, set the flag GTSAM_TANGENT_PREINTEGRATION to OFF.
```
So, is the new method turned out to be worse than the previous one or just haven't been implemented/tested yet?

Regards,

**Comment by marcusabate** [comment]
It was more unstable and error-prone. Have not tried it recently, it may be better now.
