### ISSUE TITLE
Although I am using loop closure detector by setting USE_LCD=1 I got the following image as the end point should be equal to the start point which is not implemented in my case 

### ISSUE THREAD

**Issue by omarosamahu** [MIT-SPARK/Kimera-VIO#18]
![Screenshot from 2019-11-18 13-23-22](https://user-images.githubusercontent.com/8967083/69048835-216c0e80-0a07-11ea-8a81-4540a8c50ca5.png)

**Comment by ToniRV** [comment]
@omarosamahu you can change how likely Kimera is to detect loop closures by changing the parameter alpha, default is:
```
alpha: 0.001
```
The parameter is in here https://github.com/MIT-SPARK/Kimera-VIO/blob/master/params/LCDParameters.yaml

**Comment by omarosamahu** [comment]
Nothing changed after modifying the alpha parameter and the problem still exist
