### ISSUE TITLE
Can Kimera-VIO using opencv installed in Ubuntu before?

### ISSUE THREAD

**Issue by Z-Jeff** [MIT-SPARK/Kimera-VIO#184]
When I run "catkin_build", opencv3_catkin always fails. 
It reports errors like this:
```
/usr/local/include/Imath/ImathBox.h:59:22: error: ‘IMATH_CONSTEXPR14’ does not name a type
   59 |     IMATH_HOSTDEVICE IMATH_CONSTEXPR14 Box() IMATH_NOEXCEPT;
...
/usr/local/include/Imath/ImathBox.h:141:13: error: ‘V2s’ was not declared in this scope; did you mean ‘Imath_2_4::V2s’?
  141 | typedef Box<V2s> Box2s;
...
```
It seems to be Imath problem and I don't know how to solve this, so is there a way that use opencv installed in Ubuntu and not build opencv3_catkin?

**Comment by marcusabate** [comment]
Will need more information; what distribution are you on, what version of opencv are you using, are you using `catkin build` or `catkin_make` (unclear from your inclusion of the underscore)?
