### ISSUE TITLE
Adding IMU trajectory 

### ISSUE THREAD

**Issue by omarosamahu** [MIT-SPARK/Kimera-VIO#19]
Is it supported in the code to show IMU path trajectory ??

**Comment by ToniRV** [comment]
IMU only? I'm afraid we do not display that.
Nevertheless, we have jupyter notebooks to assess the IMU pre-integration performance from the past keyframe.
These notebooks will be released soon, but are not yet present.

**Comment by rginjapan** [comment]
> IMU only? I'm afraid we do not display that.
> Nevertheless, we have jupyter notebooks to assess the IMU pre-integration performance from the past keyframe.
> These notebooks will be released soon, but are not yet present.

Thanks! Have this notebook been released now?
