### ISSUE TITLE
No such file or directory  #include <kimera-vio/pipeline/Pipeline-definitions.h

### ISSUE THREAD

**Issue by alkaChoudhary** [MIT-SPARK/Kimera-VIO#190]
**Description:**

**Command:**
```
cmake ../../src/Kimera-VIO-ROS/
make
```

**Console output:**
```
[  0%] Built target actionlib_msgs_generate_messages_eus
[  7%] Building CXX object CMakeFiles/kimera_vio_ros.dir/src/KimeraVioRos.cpp.o
In file included from /src/Kimera-VIO-ROS/src/KimeraVioRos.cpp:7:0:
/src/Kimera-VIO-ROS/include/kimera_vio_ros/KimeraVioRos.h:9:10: fatal error: kimera-vio/pipeline/Pipeline-definitions.h: No such file or directory
 #include <kimera-vio/pipeline/Pipeline-definitions.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/kimera_vio_ros.dir/build.make:62: recipe for target 'CMakeFiles/kimera_vio_ros.dir/src/KimeraVioRos.cpp.o' failed
make[2]: *** [CMakeFiles/kimera_vio_ros.dir/src/KimeraVioRos.cpp.o] Error 1
CMakeFiles/Makefile2:2632: recipe for target 'CMakeFiles/kimera_vio_ros.dir/all' failed
make[1]: *** [CMakeFiles/kimera_vio_ros.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Additional files:**
Please attach all the files needed to reproduce the error.

Please give also the following information:
* Kimera-Vio branch, tag or commit used - master
* GTSAM version used: master ( https://github.com/borglab/gtsam.git)
* OpenGV version used: master (https://github.com/laurentkneip/opengv.git)
* OpenCV version used: type `opencv_version` master (https://github.com/opencv/opencv.git)
* Operating system and version (e.g. Ubuntu 16.04 or Windows 10): Ubuntu 16.04
* Did you change the source code? (yes / no): no

**Comment by marcusabate** [comment]
If you are building in ROS you'll just use `catkin build` instead of `cmake` and `make`. Refer to installation instructions [here](https://github.com/MIT-SPARK/Kimera-VIO-ROS/#b-kimeravio-ros-wrapper-installation) If you are building native:

```
cd Kimera-VIO
mkdir build
cd build
cmake ../
make -j$(nproc)
```
