### ISSUE TITLE
error while compilng kimera-vio[BUG]

### ISSUE THREAD

**Issue by BIT-TYJ** [MIT-SPARK/Kimera-VIO#194]
Hello, thanks for your great work!
I have run Hydra without kimera-vio successfully.
However, when I added kimera-vio and tried to compile it, the following error occurred. 
**Describe the bug**
'identity' is not a member of ’gtsam::Pose3‘ 

Can you help me?

**Comment by nathanhhughes** [comment]
Also, note I transferred this to the Kimera-VIO repo as it was not related to Hydra

**Comment by wolfcanli** [comment]
> Also, note I transferred this to the Kimera-VIO repo as it was not related to Hydra

Thank you for your reply. I had the same problem.  Next, I will try the method you mentioned.
