### ISSUE TITLE
error in building dependency DBoW2 

### ISSUE THREAD

**Issue by mgrallos** [MIT-SPARK/Kimera-VIO#204]
**Description:**
Trying to implement a [visual SLAM](https://github.com/surfii3z/openvslam/tree/aigc_ekf) and DBoW2 is a dependency 

**Command:**
```
 catkin build 
``` 

**Console output:**
```

CMake Error at /home/mariah/tello_ws1/src/openvslam/ros/src/openvslam/CMakeLists.txt:202 (find_package):
  By not providing "FindDBoW2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DBoW2", but
  CMake did not find one.

  Could not find a package configuration file provided by "DBoW2" with any of
  the following names:

    DBoW2Config.cmake
    dbow2-config.cmake

  Add the installation prefix of "DBoW2" to CMAKE_PREFIX_PATH or set
  "DBoW2_DIR" to a directory containing one of the above files.  If "DBoW2"
  provides a separate development package or SDK, be sure it has been
  installed.


```

**Additional files:**
Please attach all the files needed to reproduce the error.

Please give also the following information:
* Kimera-Vio branch, tag or commit used
* GTSAM version used: no idea 
* OpenGV version used: I have no idea 
* OpenCV version used: type `opencv_version` 4.2.0 
* Operating system and version (e.g. Ubuntu 16.04 or Windows 10): Ubuntu 20 
* Did you change the source code? (yes / no): no

**Comment by marcusabate** [comment]
Make sure to install DBow2, refer to the installation instructions in the docs.
