### ISSUE TITLE
question for plane detection and mesher outputs for backend

### ISSUE THREAD

**Issue by xingyi5166** [MIT-SPARK/Kimera-VIO#206]
Hi, I have two questions about the Mesher module that I want to confirm.

1, I did not see you call the plane detection related functions in the Mesher module although you put some related functions in the code. Is that correct?

2, I did not see you pass any outputs (from the Mesher) back to the backend (pose optimization & loop closure) for further optimization. Is that correct?

Thank you so much for your time! I really appreciate it.

**Comment by marcusabate** [comment]
Both of these are correct at this time. For joint pose-mesh optimization, we use `Kimera-PGMO` (located [here](github.com/mit-spark/kimera-pgmo).
