### ISSUE TITLE
Using Iphone sensor with Kimera

### ISSUE THREAD

**Issue by hyeonmin11** [MIT-SPARK/Kimera-VIO#212]
HI, I have a question about the sensor which can use with Kimera.
Can I use Kimera with Iphone sensor?
Thanks.

**Comment by marcusabate** [comment]
I haven't looked into it, if you're able to get a decent rate video stream from the iPhone along with inertial measurements, it should be feasible. But I am not aware of what kind of SDK is available for this purpose. 
It seems from papers like [these](https://arxiv.org/pdf/2106.12186.pdf) that it's been done before, but we haven't tried it and don't have parameters for you.
