### ISSUE TITLE
Support for d435 + T265

### ISSUE THREAD

**Issue by FPSychotic** [MIT-SPARK/Kimera-VIO#22]
Hi, I would ask support for Realsense d435 plus T265 combo. It is due to it is the most powerful solution for VIO,VSLAM from Intel. Te main reason is that this combo apart to improve the performance over a d435i alone, it would release to the computer of a big part of the computing load, allowing the implementation of your software on smaller robots.
I dont know if your software as already a total or partial suport to this combo, maybe via external odometry msg, I couldnt find any mention to that feature.
Thank you

**Comment by ToniRV** [comment]
Looks very promising. We haven't tested Kimera-VIO with this hardware, it could be interesting to add support to that, thanks!
