### ISSUE TITLE
Scale Drift optimization

### ISSUE THREAD

**Issue by omarosamahu** [MIT-SPARK/Kimera-VIO#26]
I have tested the estimated trajectory compared to the ground-truth data using 
[https://github.com/uzh-rpg/rpg_trajectory_evaluation] analysis tool before and after the modification of the code and I have noticed that the scale drift err has increased as described in the attached files 
![kimera_estimated_trajs](https://user-images.githubusercontent.com/8967083/72242271-acc1e480-35f1-11ea-8db3-97eaec150f2b.png)
![scale_drift](https://user-images.githubusercontent.com/8967083/72242282-b21f2f00-35f1-11ea-9d49-8fa3ad8ef418.png)

**Comment by ToniRV** [comment]
Thanks! Do you remember which commits you were comparing?

**Comment by omarosamahu** [comment]
I have compared between "d00b5af6f7aabd85dcb2cbab0a908722b203da4f" and "aca75f72a0aa1f7af688b6c49f0d4ef2dc704d20"
