### ISSUE TITLE
Can I use RGBD camera such as realsense or kinect ?

### ISSUE THREAD

**Issue by nyxrobotics** [MIT-SPARK/Kimera-VIO#31]
Hi,
I am searching for 3D SLAM with color mesh.
Can I use kinect or realsense for this package ? Only supports stereo-camera such as ZED ?
Regards,

nyxrobotics

**Comment by ToniRV** [comment]
Hi @nyxrobotics, we support stereo and RGB-D cameras.
Concerning RGB-D, we are actively developing on the RealSense D345i and will soon support the Kinect camera as well.

**Comment by nyxrobotics** [comment]
Thank you for your information. I have D435i. 
Looking forward to your updates !

**Comment by JonasWeigand** [comment]
Hi @ToniRV,
what is the status of this subject? Our group is interessted in using the Azure Kinect with KIMERA. Are there any best practices of how to setup up KIMERA for this camera?
