### ISSUE TITLE
Support for non-identity T_BS IMU extrinsics

### ISSUE THREAD

**Issue by ruffsl** [MIT-SPARK/Kimera-VIO#41]
In robotics, sensors are often calibrated with respect to a `base_link` reference frame, relative to chassis of the robot platform. These extrinsics are often practically captured via a TF tree:

http://wiki.ros.org/tf2

For single sensor devices, such as like a free handed visual inertial camera, assuming the IMU sensor to be this base frame for the entire robot platform can be a reasonable choice. However, for larger platforms where the sensors are mounted onto robotic extremities, such as pan tilting heads, or kinematic arms, such assumptions in using the IMU as the `base_link` reference frame are no longer practical. I'd like to suggest supporting non-identity IMU extrinsics to better leverage the use of TF trees to initialize and/or update sensor extrinsics for tracking generalizable `base_link` reference frame.

This could allow ROS wrappers set the imu and stereo frame extrinsics using the most recent TF as published by calibrated URDFs, or sensor drivers that are most aware of the sensor hardware.

It looks like the `ImuParams` for the IMU front end checks to ensure the IMU is chosen as the body frame

https://github.com/MIT-SPARK/Kimera-VIO/blob/a5109c7157482bb1203918512ef6593e226507f7/src/imu-frontend/ImuFrontEndParams.cpp#L59-L66

From the snippet above, it also looks like the Pose3 `body_Pose_cam` variable parsed from the IMU config remains un-used in the rest of the pipeline.

**Comment by marcusabate** [comment]
We don't currently have plans to support non-identity extrinsics, however we do see the benefit on other robotic platforms. Given how long it's been I will close for now, but if you're still interested feel free to reopen.
