### ISSUE TITLE
Number of distortion_coefficients

### ISSUE THREAD

**Issue by omarosamahu** [MIT-SPARK/Kimera-VIO#47]
I have calibrated my camera with distortion_model : "radial-tangential" using kalibr .I found that the number of  distortion_coefficients you used inside calibration is 4 parameters ,However the output number  from kalibr is 5 parameters for the same distortion_model .Plz advise

**Comment by marcusabate** [comment]
Kalibr should only output 4 for radtan. I will close for now given how long it's been, any future visitors are welcome to reopen if there is some change to Kalibr that I'm not aware of.
