### ISSUE TITLE
Support for Ubuntu 20.04 LTS and OpenCV v4.2

### ISSUE THREAD

**Issue by ruffsl** [MIT-SPARK/Kimera-VIO#60]
With Ubuntu 20.04 LTS now shipping with OpenCV v4.2 , it would be nice update Kimera-VIO to support the latest long term support release of Ubuntu Focal and ROS releases Noetic and Foxy:

https://packages.ubuntu.com/focal/libopencv-dev

This should just evolve updating Kimera-VIO to transition it away from APIs that where deprecated in OpenCV v3 and removed in v4. From an initial look over, it seems that some of the c type headers will have to be explicitly imported, and switching to use the proper enum types for function arguments.

**Comment by ToniRV** [comment]
Thank you @ruffsl !
I'll comment on the PR
