### ISSUE TITLE
baseline calculation in Camera.h assumes axis-aligned camera

### ISSUE THREAD

**Issue by jingnanshi** [MIT-SPARK/Kimera-VIO#67]
**Description:**

The calculation of baseline in `Camera.h` assumes an axis-aligned stereo camera setup. Specifically, it assumes the two cameras are on the x-axis. Using the norm to calculate baseline will be better.
https://github.com/MIT-SPARK/Kimera-VIO/blob/42ad9ca557656ef3463b8cc3b841fe5a4a36398c/include/kimera-vio/frontend/Camera.h#L262

**Comment by ToniRV** [comment]
Checking the norm is not enough, but I'll add a warning if the baseline is not along x axis after rectification.
