### ISSUE TITLE
Seek for your help!

### ISSUE THREAD

**Issue by Sandeldeng** [MIT-SPARK/Kimera-VIO#7]
I want to know which version should I used. because I have mistake when i build Kimera-VIO.
/usr/local/include/gtsam/base/Vector.h:72:1: error: static assertion failed: Error: GTSAM was built against a different version of Eigen.

**Comment by jingnanshi** [comment]
Did you follow this: https://github.com/MIT-SPARK/Kimera-VIO/blob/master/docs/kimeravio_installation.md?
