### ISSUE TITLE
Mono-only capabilities release date

### ISSUE THREAD

**Issue by rastinrastini** [MIT-SPARK/Kimera-VIO#81]
Dear,
thanks for this code.
have any release date for mono-only capability while you wrote "Mono-only capabilities soon to be released"?
Thankful.

**Comment by ToniRV** [comment]
@rastinrastini unfortunately I am caught with some deadlines so I won't be able to release this before the summer ends :(

**Comment by aseyfi** [comment]
Hi @ToniRV ,

Thank you for sharing this code. Any updates on releasing mono-only feature?

Thanks,
Ahmad

**Comment by ToniRV** [comment]
We are currently working on it.
First week of October would be a reasonable deadline if all goes well.

**Comment by aseyfi** [comment]
Thanks @ToniRV for the quick response. Based on what I see in [issue-9](https://github.com/MIT-SPARK/Kimera-VIO/issues/9), it seems we already can use mono+IMU odometry. Would you please confirm?

**Comment by jaadelgren** [comment]
Also interested in this, any update?

**Comment by ToniRV** [comment]
> Thanks @ToniRV for the quick response. Based on what I see in issue-9, it seems we already can use mono+IMU odometry. Would you please confirm?

Technically yes, but there are some sections of the code that still assume Stereo: we are currently working on making the whole pipeline also work in the mono-only case.

**Comment by sathishkumark27** [comment]
@ToniRV 
Thanks for the great work. does mono-only means mono without IMU? Do you have any update on the mono-only?

Thanks & Regards
Sathish

**Comment by danigr99727** [comment]
any updates on this? I have tried to run the code with mono-only euroc, without success.

**Comment by DamDsj** [comment]
@ToniRV 
Is there any update concerningthe mono+imu feature? Is there a branch/patch where we could try this out?
Thanks
Regards
Damien

**Comment by neo-knight-td** [comment]
@ToniRV, 
Any update concerning monocular ?

**Comment by ToniRV** [comment]
Hi everyone, yes, we will be pushing the mono+imu version soon (this week!).

**Comment by bednarhonza** [comment]
I believe here #152 is the pull request for the mono feature.

**Comment by ToniRV** [comment]
Yes, PR is #152 :+1:

**Comment by aseyfi** [comment]
@ToniRV , thank you very much for releasing this code. I have been able to run the dockers  you have provided, but I would like to use kimera mono with ROS. Does the ROS wrapper support kimera mono?

Thank You,
Ahmad

**Comment by marcusabate** [comment]
@aseyfi The associated ROS PR is on its way, maybe another day or two.

**Comment by yhabib29** [comment]
Could you give more details on which functionalities won't be available in monocular mode please ?

**Comment by johnsmakar** [comment]
Is loop closure available for mono?
