### ISSUE TITLE
Error on Running Kimera-VIO in Euroc's dataset

### ISSUE THREAD

**Issue by rttariverdi67** [MIT-SPARK/Kimera-VIO#83]
Dear repository,
Could you please help me with following problem? I followed Installation instructions and download one of Euroc's datasets "V1_01_easy.zip" but while running :
bash/scripts/stereoVIOEuroc.bash -p "PATH_TO_DATASET/V1_01_easy" 

I got an error as follows:

 
Using dataset at path: PATH_TO_DATASET/V1_01_easy
 Launching:

            ██╗  ██╗██╗███╗   ███╗███████╗██████╗  █████╗
            ██║ ██╔╝██║████╗ ████║██╔════╝██╔══██╗██╔══██╗
            █████╔╝ ██║██╔████╔██║█████╗  ██████╔╝███████║
            ██╔═██╗ ██║██║╚██╔╝██║██╔══╝  ██╔══██╗██╔══██║
            ██║  ██╗██║██║ ╚═╝ ██║███████╗██║  ██║██║  ██║
            ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝

 
I0602 14:16:07.021721  8221 RegularVioBackEnd.cpp:114] Using Regular VIO backend.
I0602 14:16:07.023967  8221 PipelineModule.h:450] MISO Pipeline Module: Display has no output queue registered.
I0602 14:16:07.024134  8222 EurocDataProvider.cpp:98] Parsing Euroc dataset...
I0602 14:16:07.024147  8223 Pipeline.h:184] Spinning Kimera-VIO.
F0602 14:16:07.024188  8222 EurocDataProvider.cpp:201] Cannot open file: PATH_TO_DATASET/V1_01_easy/mav0/imu0/data.csv
*** Check failure stack trace: ***
I0602 14:16:07.024219  8224 Pipeline.cpp:375] Shutting down VIO pipeline once processing has finished.
I0602 14:16:07.024405  8224 Pipeline.cpp:449] Statistics
-----------                                  #	Log Hz	{avg     +- std    }	[min,max]
Data Provider [ms]                      	    0	
Display [ms]                            	    0	
backend_input_queue Size [#]            	    0	
data_provider_left_frame_queue Size [#] 	    0	
data_provider_right_frame_queue Size [#]	    0	
display_input_queue Size [#]            	    0	
stereo_frontend_input_queue Size [#]    	    0	
visualizer_backend_queue Size [#]       	    0	
visualizer_frontend_queue Size [#]      	    0	
    @     0x7fb9bbe410cd  google::LogMessage::Fail()
    @     0x7fb9bbe42f33  google::LogMessage::SendToLog()
    @     0x7fb9bbe40c28  google::LogMessage::Flush()
    @     0x7fb9bbe43999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb9bd28739f  VIO::EurocDataProvider::parseImuData()
    @     0x7fb9bd28bf62  VIO::EurocDataProvider::parseDataset()
    @     0x7fb9bd28c718  VIO::EurocDataProvider::parse()
    @     0x7fb9bd28cb45  VIO::EurocDataProvider::spin()
    @     0x557c4f575643  (unknown)
    @     0x557c4f575959  (unknown)
    @     0x7fb9bb5fe827  __pthread_once_slow
    @     0x557c4f576db4  (unknown)
    @     0x557c4f5770c7  (unknown)
    @     0x7fb9bb3236df  (unknown)
    @     0x7fb9bb5f66db  start_thread
    @     0x7fb9bad7e88f  clone
./scripts/stereoVIOEuroc.bash: line 109:  8221 Aborted                 (core dumped) $BUILD_PATH/stereoVIOEuroc --dataset_type="$DATASET_TYPE" --dataset_path="$DATASET_PATH" --initial_k=50 --final_k=2000 --params_folder_path="$PARAMS_PATH" --use_lcd="$USE_LCD" --vocabulary_path="$VOCABULARY_PATH/ORBvoc.yml" --flagfile="$PARAMS_PATH/flags/stereoVIOEuroc.flags" --flagfile="$PARAMS_PATH/flags/Mesher.flags" --flagfile="$PARAMS_PATH/flags/VioBackEnd.flags" --flagfile="$PARAMS_PATH/flags/RegularVioBackEnd.flags" --flagfile="$PARAMS_PATH/flags/Visualizer3D.flags" --logtostderr=1 --colorlogtostderr=1 --log_prefix=1 --v=0 --vmodule=Pipeline*=00 --log_output="$LOG_OUTPUT" --log_euroc_gt_data="$LOG_OUTPUT" --save_frontend_images=1 --visualize_frontend_images=1 --output_path="$OUTPUT_PATH"

**Comment by ToniRV** [comment]
Here is the problem:
```
F0602 14:16:07.024188 8222 EurocDataProvider.cpp:201] Cannot open file: PATH_TO_DATASET/V1_01_easy/mav0/imu0/data.csv
*** Check failure stack trace: ***
```
Make sure you specify the correct path to the euroc dataset
