### ISSUE TITLE
details about point clouds

### ISSUE THREAD

**Issue by rttariverdi67** [MIT-SPARK/Kimera-VIO#86]
- while running dataset, what is the difference between points which are generated ?(red, blue, green), can I say they're tracked features from different cameras(cam0, cam1, imu0) ?
also I want to ask for some comments about the descriptors that you have used in Kimera. if there are some links that would be perfect if you shear.

**Comment by marcusabate** [comment]
Red are landmarks that are not tracked from previous frames (failed tracking).
Blue are new feature tracks.
Green are features tracked from previous frames.
We use GoodFeaturesToTrack (https://docs.opencv.org/3.4/d4/d8c/tutorial_py_shi_tomasi.html)
