### ISSUE TITLE
Will this work with IntelRealsense T265 camera?

### ISSUE THREAD

**Issue by masterchop** [MIT-SPARK/Kimera-VIO#98]
I notice that you can use the D455 on this code but i wonder if its possible to use the IntelReal Sense T265 ?

Info about the camera: https://www.intelrealsense.com/tracking-camera-t265/

**Comment by ToniRV** [comment]
We are giving a try to this camera as well! Will update as soon as we get results.
It should definitely be possible to run Kimera on it.
