### ISSUE TITLE
How to use KITTI dataset in example/KimeraVIO.cpp

### ISSUE THREAD

**Issue by zzzzzzli** [MIT-SPARK/Kimera-VIO#99]
Thank you very much for this library to use.
I noticed that the Data provider module contains KITTI dataset function, but in the example program KimeraVIO.cpp, it doesn't support KITTI dataset. When I run it with the option `-d 1` to use KITTI dataset, it occurs a error "core dumped".
How to use KITTI dataset in this example? Thank you very much.

**Comment by ToniRV** [comment]
Hi @zzzzzzli , we dropped support for KITTI currently, because we had issues with the IMU data (which is very sparse).
